### ISSUE TITLE
Junos Guest VM not starting

### ISSUE THREAD

**Issue by piotr-kochanowski** [dgarros/guestvm-coreos#1]
I was following your guide to run coreos on Juniper QFX 5100-48t-6q.
Short summary of what I did:

- image copy to junos: coreos-production-qemu-raw.img.gz
- request system software add..

root# run show version
fpc0:
--------------------------------------------------------------------------
Model: qfx5100-48t-6q
Junos: 17.3R3-S1.5 limited
---
JUNOS GUEST-VM Software [coreos-production-qemu-raw-ve]

root# show services app-engine
compute-cluster default-cluster {
    compute-node default-node {
        hypervisor;
    }
}
virtual-machines {
    instance COREOS {
        management-interface em1;
        package coreos-production-qemu-raw-ve;
        local-management {
            family inet {
                address 192.168.1.101;
            }
        }
        compute-cluster default-cluster {
            compute-node default-node;
        }
    }
}
root# run show app-engine virtual-machine instance
VM name                  Compute cluster           VM status
COREOS                   default-cluster           UNAVAILABLE [VM does not exist]

I've found some errors in /var/log/messages on Junos Host OS:

Nov 26 13:32:15 localhost vehostd[7106]: guest_show_error, libvirt reported error: "Domain not found: no domain with matching name 'COREOS'", code 42, lib_domain 10, level 2
Nov 26 13:32:15 localhost vehostd[7106]: guest_vm_check_storage, guest domain not found, virt_error_code 42
Nov 26 13:32:15 localhost vehostd[7106]: guest_show_error, libvirt reported error: "Domain not found: no domain with matching name 'COREOS'", code 42, lib_domain 10, level 2
Nov 26 13:32:15 localhost vehostd[7106]: guest_vm_check_storage, guest domain not found, virt_error_code 42
Nov 26 13:32:15 localhost vehostd[7106]: guest_show_error, libvirt reported error: "internal error: process exited while connecting to monitor: qemu-kvm: -drive file=/var/third-party/disks/guest_info_disk.img,if=none,id=drive-virtio-disk1,format=raw,cache=none: Duplicate ID 'drive-virtio-disk1' for drive#012", code 1, lib_domain 10, level 2
Nov 26 13:32:20 localhost vehostd[7106]: guest_show_error, libvirt reported error: "Domain not found: no domain with matching name 'COREOS'", code 42, lib_domain 10, level 2
Nov 26 13:32:20 localhost vehostd[7106]: guest_create: Domain creation failed, virt_error_code 42
Nov 26 13:32:23 localhost vehostd[7106]: guest_show_error, libvirt reported error: "Domain not found: no domain with matching name 'COREOS'", code 42, lib_domain 10, level 2
Nov 26 13:32:23 localhost vehostd[7106]: guest_get_info, guest domain not found COREOS, virt_error_code 42

**Comment by dgarros** [comment]
@piotr-kochanowski I'm sorry but I don't work at Juniper anymore so I won't be able to help here.

I created this project long time ago when the architecture of the QFX5100 was different, I wouldn't be surprised if this project is not applicable to the latest junos version.

good luck with your research
